# Generated by Django 4.2.3 on 2023-11-14 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_channelsform_delete_channelform'),
    ]

    operations = [
        migrations.AddField(
            model_name='channelsform',
            name='channelimage',
            field=models.ImageField(default=1, upload_to='images'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='channelsform',
            name='channelthumble',
            field=models.ImageField(default=5, upload_to='bigimages'),
            preserve_default=False,
        ),
    ]
