# Generated by Django 4.1.3 on 2023-11-14 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_channelsform_channelimage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channelsform',
            name='channelimage',
            field=models.ImageField(upload_to='channelimages'),
        ),
        migrations.AlterField(
            model_name='channelsform',
            name='channelthumble',
            field=models.ImageField(upload_to='thumblebigimages'),
        ),
    ]
