# Generated by Django 4.2.3 on 2023-11-15 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_channelsform_channelimage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channelsform',
            name='channelimage',
            field=models.ImageField(upload_to='cimg'),
        ),
        migrations.AlterField(
            model_name='channelsform',
            name='channelthumble',
            field=models.ImageField(upload_to='timg'),
        ),
    ]
