# Generated by Django 4.2.3 on 2023-11-15 10:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_channelsform_channelimage_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='channelsform',
            old_name='channelimage',
            new_name='channelimages',
        ),
        migrations.RenameField(
            model_name='channelsform',
            old_name='channelthumble',
            new_name='channelthumbles',
        ),
    ]
