# Generated by Django 4.2.3 on 2023-11-15 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_rename_channelimage_channelsform_channelimages_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channels',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chann', models.ImageField(upload_to='limg')),
            ],
        ),
    ]
