# Generated by Django 4.1.3 on 2023-11-15 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_channels'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Channels',
        ),
    ]
