# Generated by Django 4.1.3 on 2023-11-15 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_channelvideo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channelvideo',
            name='channelimages',
            field=models.ImageField(upload_to='videosimage'),
        ),
        migrations.AlterField(
            model_name='channelvideo',
            name='channelthumbles',
            field=models.FileField(upload_to='videos'),
        ),
    ]
