# Generated by Django 4.2.3 on 2023-11-16 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_channelvideo_smallimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='channelvideo',
            name='channelname',
            field=models.CharField(default=5, max_length=255),
            preserve_default=False,
        ),
    ]
