# Generated by Django 4.2.3 on 2023-11-17 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_subscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='channelsform',
            name='subscibers',
            field=models.IntegerField(default=0),
        ),
    ]
