# Generated by Django 4.2.3 on 2023-11-17 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_channelsform_subscibers'),
    ]

    operations = [
        migrations.AddField(
            model_name='channelvideo',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
