# Generated by Django 4.2.3 on 2023-11-17 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0017_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='subscribers',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.CASCADE, to='myapp.channelvideo'),
            preserve_default=False,
        ),
    ]
