# Generated by Django 4.2.3 on 2023-11-17 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_subscription_subscribers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='subscribers',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.channelsform'),
        ),
    ]
