# Generated by Django 4.2.3 on 2023-11-17 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_alter_subscription_subscribers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='subscribers',
            new_name='channelsubscribers',
        ),
    ]
