# Generated by Django 4.1.3 on 2023-11-18 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0022_rename_mylist_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='channelvideo',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
