# Generated by Django 4.1.3 on 2023-11-18 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0030_shorts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shorts',
            name='shortvideo',
            field=models.FileField(upload_to='shortsvideos'),
        ),
    ]
