# Generated by Django 4.1.3 on 2023-11-18 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0031_alter_shorts_shortvideo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shorts',
            name='channelname',
        ),
        migrations.AddField(
            model_name='shorts',
            name='shortchannelname',
            field=models.CharField(default=5, max_length=255),
            preserve_default=False,
        ),
    ]
