# Generated by Django 4.1.3 on 2023-11-18 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0032_remove_shorts_channelname_shorts_shortchannelname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shorts',
            name='slug',
            field=models.IntegerField(default=0),
        ),
    ]
