# Generated by Django 4.1.3 on 2023-11-18 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0033_alter_shorts_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channelvideo',
            name='slug',
            field=models.IntegerField(default=0),
        ),
    ]
